[project]
name = 'Blockchain-Based-Healthcare-Precision-Prevention'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.individual-verification]
path = 'contracts/individual-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.intervention-tracking]
path = 'contracts/intervention-tracking.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
